name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        cd wasm
        RUSTFLAGS='--cfg getrandom_backend="wasm_js"' wasm-pack build --target web --dev
